version: '3'

tasks:
  run_playbook:
    desc: Run the Ansible playbook to execute gitops-toolkit role
    cmds:
      - ansible-playbook ./playbook.yml
  delete:
    desc: Delete all clusters
    cmds:
      - k3d cluster delete --all
  clean:
    desc: Clean up cache
    cmds:
      - rm -rf .cache
