version: '3'

tasks:
  install_role:
    desc: Install the pinned gitops-toolkit role dependency
    cmds:
      - ansible-galaxy install -r requirements.yml -v -p ./roles --force

  run_playbook:
    desc: Run the Ansible playbook to execute gitops-toolkit role
    cmds:
      - ansible-playbook ./playbook.yml

  delete:
    desc: Delete all clusters
    cmds:
      - k3d cluster delete --all

  clean:
    desc: Clean up cache
    cmds:
      - rm -rf .cache
